Support for PL1_LINKTRAIN_CMD and updated linkstatus counters
xenanetworks/open-automation-python-api pull request #63
Opened 2023-01-16 10:51 UTC by MichaelLilja-Xena

Signed-off-by: Michael Lilja <mli@xenanetworks.com>

2023-01-16 15:16 UTC, leonardhyu commented
@ArtemConstantinov Michal is contributing to the LL-API by adding some L1-related commands for ANLT. I don't find anything that can create conflicts. Your call will be the final one on this pull request.

2023-01-17 01:18 UTC, ArtemConstantinov reviewed
In python the code style like this: 
``` python
class LinkTrainCmd(IntEnum):
  """No operation. Used for 'ping' testing"""
  CMD_NOP                     = 0
  """Increment the coeff provided in ARG"""
  CMD_INC                     = 1
  """Decrement the coeff provided in ARG"""
  CMD_DEC                     = 2
  """Set the preset provided in ARG"""
  CMD_PRESET                  = 3
  """Set encoding provided in ARG"""
  CMD_ENCODING                = 4
  """Signal training completed"""
  CMD_LOCAL_TRAINED           = 255
```
Is it a bad code practice for more details please check [PEP8](https://peps.python.org/pep-0008/#whitespace-in-expressions-and-statements) recommendations.  To make our code consistent we following PEP8 recommendations maximum as possible.

The correct example will look like:
``` python
class LinkTrainCmd(IntEnum):
  """No operation. Used for 'ping' testing"""
  CMD_NOP = 0
  """Increment the coeff provided in ARG"""
  CMD_INC = 1
  """Decrement the coeff provided in ARG"""
  CMD_DEC = 2
  """Set the preset provided in ARG"""
  CMD_PRESET = 3
  """Set encoding provided in ARG"""
  CMD_ENCODING  = 4
  """Signal training completed"""
  CMD_LOCAL_TRAINED = 255
```
To avoid this issue I can recommend using a `Flake8` linter, which can be installed via `pip install flake8` it also has integration for popular IDE's as VSCode. which will highlight issues in the editor

2023-01-17 01:34 UTC, ArtemConstantinov requested changes
In our code class names where all letters are capitalized, we apply only to command names to make them look like the commands from the Xena CLI but it is not the correct way, because all capital letters represent a constant in the python code style, please use CammelCase for all of the classes if they are not an `LLI` command, I'm not able to approve pull request till code style is not match. please see `Line: 1907 in file enums.py`. 
also, no spaces are allowed in code like: 
``` python
class ReconciliationSublayerSupport (IntEnum):
    ...
```
It supposes to be:
``` python
class ReconciliationSublayerSupport(IntEnum):
    ...
```

2023-01-17 08:44 UTC, ArtemConstantinov approved these changes

2023-01-18 12:31 UTC, merged